import jsPDF from 'jspdf';
import Papa from 'papaparse';
import { TRUNCATE } from '@/config';

/**
 * Экспорт сравнения репозиториев в PDF
 */
export function exportComparisonToPDF(data: {
    repos: Array<{
        name: string;
        owner: string;
        stars: number;
        forks: number;
        watchers: number;
        issues: number;
        contributors: number;
        languages: number;
        created: string;
        license: string;
    }>;
}) {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(20, 184, 166); // teal
    doc.text('GitHub Repository Comparison', 20, 20);

    // Date
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 30);

    // Reset color
    doc.setTextColor(0);

    let yPos = 45;

    data.repos.forEach((repo, index) => {
        // Repository Header
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(20, 184, 166); // teal
        doc.text(`${index + 1}. ${repo.owner}/${repo.name}`, 20, yPos);
        yPos += 8;

        // Metrics
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);

        const metrics = [
            `Stars: ${repo.stars.toLocaleString()}`,
            `Forks: ${repo.forks.toLocaleString()}`,
            `Watchers: ${repo.watchers.toLocaleString()}`,
            `Open Issues: ${repo.issues.toLocaleString()}`,
            `Contributors: ${repo.contributors}+`,
            `Languages: ${repo.languages}`,
            `Created: ${repo.created}`,
            `License: ${repo.license}`,
        ];

        metrics.forEach((metric) => {
            doc.text(`  - ${metric}`, 25, yPos);
            yPos += 6;
        });

        yPos += 5;

        // Добавить новую страницу если места не хватает
        if (yPos > 270 && index < data.repos.length - 1) {
            doc.addPage();
            yPos = 20;
        }
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            `Generated by GitHub Explorer - Page ${i} of ${pageCount}`,
            20,
            doc.internal.pageSize.height - 10
        );
    }

    // Download
    doc.save(`github-comparison-${Date.now()}.pdf`);
}

/**
 * Экспорт статистики репозитория в PDF
 */
export function exportRepoStatsToPDF(data: {
    name: string;
    owner: string;
    description: string;
    stars: number;
    forks: number;
    watchers: number;
    issues: number;
    language: string;
    license: string;
    created: string;
    updated: string;
    healthScore: {
        score: number;
        grade: string;
        factors: {
            activity: number;
            community: number;
            maintenance: number;
            documentation: number;
        };
    };
    contributors: Array<{ login: string; contributions: number }>;
    languages: Array<{ name: string; percentage: number }>;
    recentCommits: Array<{ message: string; author: string; date: string }>;
    issuesAnalytics: { 
        total: number;
        open: number;
        closed: number;
        avgCloseTime: number;
        topLabels: Array<{ name: string; count: number; percentage: number }>;
    };
    dependencies: {
        total: number;
        prod: number;
        dev: number;
    } | null;
}) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(20, 184, 166); // teal
    doc.text(`${data.owner}/${data.name}`, 20, 20);

    // Description
    doc.setFontSize(10);
    doc.setTextColor(100);
    const splitDescription = doc.splitTextToSize(
        data.description || 'No description',
        170
    );
    doc.text(splitDescription, 20, 30);

    let yPos = 30 + splitDescription.length * 5 + 10;

    // Main Metrics Section
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Metrics', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    const mainMetrics = [
        `Stars: ${data.stars.toLocaleString()}`,
        `Forks: ${data.forks.toLocaleString()}`,
        `Watchers: ${data.watchers.toLocaleString()}`,
        `Open Issues: ${data.issues.toLocaleString()}`,
        `Primary Language: ${data.language}`,
        `License: ${data.license}`,
        `Created: ${data.created}`,
        `Last Updated: ${data.updated}`,
    ];

    mainMetrics.forEach((metric) => {
        doc.text(`  - ${metric}`, 25, yPos);
        yPos += 7;
    });

    yPos += 10;

    // Top Contributors
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Top Contributors', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    data.contributors.slice(0, 10).forEach((contributor, index) => {
        doc.text(
            `  ${index + 1}. ${contributor.login} - ${contributor.contributions} commits`,
            25,
            yPos
        );
        yPos += 6;
    });

    yPos += 10;

    // Languages
    if (yPos > 250) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Languages Distribution', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');

    data.languages.forEach((lang) => {
        doc.text(`  - ${lang.name}: ${lang.percentage.toFixed(1)}%`, 25, yPos);
        yPos += 6;
    });

    yPos += 10;


    // HEALTH SCORE SECTION

    if (yPos > 230) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 184, 166); // teal
    doc.text('Health Score', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);

    doc.text(`  Overall Score: ${data.healthScore.score}/100 (${data.healthScore.grade})`, 25, yPos);
    yPos += 7;
    doc.text(`  Activity: ${data.healthScore.factors.activity}/100`, 25, yPos);
    yPos += 6;
    doc.text(`  Community: ${data.healthScore.factors.community}/100`, 25, yPos);
    yPos += 6;
    doc.text(`  Maintenance: ${data.healthScore.factors.maintenance}/100`, 25, yPos);
    yPos += 6;
    doc.text(`  Documentation: ${data.healthScore.factors.documentation}/100`, 25, yPos);
    yPos += 10;


    // DEPENDENCIES SECTION

    if (data.dependencies) {
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(20, 184, 166);
        doc.text('Dependencies', 20, yPos);
        yPos += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);

        doc.text(`  Total Dependencies: ${data.dependencies.total}`, 25, yPos);
        yPos += 6;
        doc.text(`  Production: ${data.dependencies.prod}`, 25, yPos);
        yPos += 6;
        doc.text(`  Development: ${data.dependencies.dev}`, 25, yPos);
        yPos += 10;
    }


    // ISSUES ANALYTICS SECTION

    if (yPos > 220) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 184, 166);
    doc.text('Issues Analytics', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);

    doc.text(`  Total Issues: ${data.issuesAnalytics.total}`, 25, yPos);
    yPos += 6;
    doc.text(`  Open: ${data.issuesAnalytics.open} (${((data.issuesAnalytics.open / data.issuesAnalytics.total) * 100).toFixed(1)}%)`, 25, yPos);
    yPos += 6;
    doc.text(`  Closed: ${data.issuesAnalytics.closed} (${((data.issuesAnalytics.closed / data.issuesAnalytics.total) * 100).toFixed(1)}%)`, 25, yPos);
    yPos += 6;
    doc.text(`  Avg Close Time: ${data.issuesAnalytics.avgCloseTime.toFixed(1)} days`, 25, yPos);
    yPos += 8;

    // Top Labels
    if (data.issuesAnalytics.topLabels.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.text('  Top Labels:', 25, yPos);
        yPos += 6;
        doc.setFont('helvetica', 'normal');
        
        data.issuesAnalytics.topLabels.forEach((label) => {
            doc.text(`    - ${label.name}: ${label.count} (${label.percentage.toFixed(1)}%)`, 25, yPos);
            yPos += 6;
        });
    }

    yPos += 10;


    // RECENT COMMITS SECTION

    if (yPos > 220) {
        doc.addPage();
        yPos = 20;
    }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 184, 166);
    doc.text('Recent Commits', 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);

    data.recentCommits.forEach((commit, index) => {
        // Обрезаем длинные сообщения
        const message = commit.message.length > TRUNCATE.COMMIT_MESSAGE_LENGTH 
            ? commit.message.substring(0, TRUNCATE.COMMIT_MESSAGE_LENGTH) + '...' 
            : commit.message;
        
        doc.text(`  ${index + 1}. ${message}`, 25, yPos);
        yPos += 5;
        doc.setTextColor(100);
        doc.text(`     By ${commit.author} on ${commit.date}`, 25, yPos);
        doc.setTextColor(0);
        yPos += 7;
    });

    yPos += 5;

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
        `Generated by GitHub Explorer on ${new Date().toLocaleDateString()}`,
        20,
        doc.internal.pageSize.height - 10
    );

    // Download
    doc.save(`${data.owner}-${data.name}-stats-${Date.now()}.pdf`);
}


// CSV EXPORT UTILITIES

/**
 * Экспорт trending репозиториев в CSV
 */
export function exportTrendingToCSV(data: {
    repos: Array<{
        rank: number;
        name: string;
        owner: string;
        description: string;
        stars: number;
        forks: number;
        language: string;
        url: string;
    }>;
    since: string;
    language?: string;
}) {
    // Подготовка данных
    const csvData = data.repos.map((repo) => ({
        Rank: repo.rank,
        Repository: `${repo.owner}/${repo.name}`,
        Description: repo.description || '',
        Stars: repo.stars,
        Forks: repo.forks,
        Language: repo.language || 'N/A',
        URL: repo.url,
    }));

    // Генерация CSV
    const csv = Papa.unparse(csvData);

    // Создание Blob и скачивание
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    const filename = `trending-${data.since}${
        data.language ? `-${data.language.toLowerCase()}` : ''
    }-${Date.now()}.csv`;

    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

/**
 * Экспорт результатов поиска в CSV
 */
export function exportSearchResultsToCSV(data: {
    repos: Array<{
        name: string;
        owner: string;
        description: string;
        stars: number;
        forks: number;
        watchers: number;
        language: string;
        url: string;
    }>;
    query: string;
}) {
    const csvData = data.repos.map((repo) => ({
        Repository: `${repo.owner}/${repo.name}`,
        Description: repo.description || '',
        Stars: repo.stars,
        Forks: repo.forks,
        Watchers: repo.watchers,
        Language: repo.language || 'N/A',
        URL: repo.url,
    }));

    const csv = Papa.unparse(csvData);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', `search-${data.query}-${Date.now()}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}
